### ISSUE TITLE
[Bug]: Potential CSP Issue in Chrome 130 

### ISSUE THREAD

**Issue by shikhir-arora** [pnd280/complexity#7]
### Version

0.0.1.5-PUBLIC-BETA

### Describe the bug

I wanted to express my gratitude for creating such an excellent extension that is open-source, well-documented, clean, and lightweight.

I typically use Chrome Canary as my daily browser. However, a recent change in CSP policies or how the browser handles them seems to be affecting the loading of the Complexity extension. I used the extension for a few days, and it worked perfectly. However, currently, only the CSS injection seems to be working. I have attached several relevant screenshots below. I have also tried everything in Incognito Mode with no other extensions enabled.

I appreciate the effort you've put into this project. Please let me know if you can reproduce this issue. 🙂 

### Steps to reproduce

Please take a look at the screenshots below! 👍

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

Normal behaviour, i.e: 
<img width="1439" alt="Untitled" src="https://github.com/user-attachments/assets/4ef74b73-1ce3-4e98-a6e9-54efb61d31cf">

### Screenshots

<img width="1234" alt="Screenshot 2024-09-01 at 7 24 51 PM" src="https://github.com/user-attachments/assets/3fe89155-b199-464f-874d-e29607964aaf">
<img width="3168" alt="Screenshot 2024-09-01 at 7 24 21 PM" src="https://github.com/user-attachments/assets/442b435f-3113-4d63-b9fd-c174b5e8e198">
<img width="2981" alt="Screenshot 2024-09-01 at 7 19 17 PM" src="https://github.com/user-attachments/assets/8765d55d-869f-42a9-a96a-417fa29555df">
<img width="2949" alt="Screenshot 2024-09-01 at 7 00 40 PM" src="https://github.com/user-attachments/assets/1e01cdcf-544a-496d-8b3d-0a17a920141c">
<img width="2655" alt="Screenshot 2024-09-01 at 6 56 39 PM" src="https://github.com/user-attachments/assets/e17f4f52-2e6b-4e2b-a740-307f31eafbe9">

### Browser

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

**Comment by pnd280** [comment]
ce9242a0538e86b88ee455b2dea55598f6c779db should fix the issue. The fix is somewhat hacky since @crxjs/vite-plugin doesn't have an option to disable `use_dynamic_url`, which is most likely the cause that triggers the CSP

https://github.com/pnd280/complexity/releases/tag/v0.0.1.6-alpha

**Comment by shikhir-arora** [comment]
@pnd280 - Thank you, it works great! 👍

**Comment by bruceeewong** [comment]
@pnd280 Hey, first of all, thank you for the brilliant hack, it worked for build version. However, for dev mode, crxjs would always append an entry of web_accessible_resources, which causes the extension fail to be loaded by the latest Chrome. Do you have the same issue?

```
{
  "matches": ["<all_urls>"],
  "resources": ["**/*", "*"],
  "use_dynamic_url": true
}
```

**Comment by pnd280** [comment]
> @pnd280 Hey, first of all, thank you for the brilliant hack, it worked for build version. However, for dev mode, crxjs would always append an entry of web_accessible_resources, which causes the extension fail to be loaded by the latest Chrome. Do you have the same issue?
> 
> ```
> {
>   "matches": ["<all_urls>"],
>   "resources": ["**/*", "*"],
>   "use_dynamic_url": true
> }
> ```

my solution works for both dev and build env, as long as it purges all `"use_dynamic_url": true`s

**Comment by Ang-l** [comment]
> > @pnd280 Hey, first of all, thank you for the brilliant hack, it worked for build version. However, for dev mode, crxjs would always append an entry of web_accessible_resources, which causes the extension fail to be loaded by the latest Chrome. Do you have the same issue?
> > ```
> > {
> >   "matches": ["<all_urls>"],
> >   "resources": ["**/*", "*"],
> >   "use_dynamic_url": true
> > }
> > ```
> 
> my solution works for both dev and build env, as long as it purges all `"use_dynamic_url": true`s

@pnd280 Hello, the solution I used from you still cannot solve it.

**Comment by pnd280** [comment]
@Ang-l please continue discussion in the original issue https://github.com/crxjs/chrome-extension-tools/issues/918
